apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nodejs-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/nodejs-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-project
  targetNamespace: nodejs-app
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
