apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nodejs-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/<your-github-username>/fluxcd-nodejs-app
  ref:
    branch: main
