apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nodejs-app
  namespace: default
spec:
  interval: 1m
  releaseName: nodejs-app
  chart:
    spec:
      chart: ./charts/nodejs-app
      sourceRef:
        kind: GitRepository
        name: nodejs-app
        namespace: flux-system
      interval: 1m
  values:
    # You can override chart values here if needed
