apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs-app
  namespace: nodejs-app
spec:
  interval: 5m
  path: ./apps/nodejs-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-project
  targetNamespace: nodejs-app
