apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 5m
  releaseName: fluxcd
  chart:
    spec:
      chart: flux2
      version: '2.10.0'
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
      interval: 5m
  values: {}
