apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./fluxcd/fluxcd-resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: nodejs-app
  targetNamespace: default
