apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  path: ./argocd/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-argocd-deployments
  targetNamespace: ingress-nginx
  wait: true
