apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./prometheus-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-argocd-deployments
  targetNamespace: monitoring
  wait: true
